name: StrongholdsandEnderdragons
version: "InDev 2.0"
main: avernusvenine.sne.StrongholdsAndEnderdragons
api-version: '1.20'
depend: [Citizens]
commands:
  GiveCustomItem:
    description: Gives a custom item to the player
    usage: /<command> item_id
  SetRank:
    description: Sets a player to a given rank
    usage: /<command> username rank
  GetRank:
    description: Gets a players rank
    usage: /<command> username
  OpenGUI:
    description: Opens a gui to the player
    usage: /<command> gui_id
  SpawnNPC:
    description: Spawns an NPC on the player
    usage: /<command> npc_id
  ShowTitle:
    description: Used to test negative spacing fonts
    usage: /<command> spacing
  DespawnNPC:
    description: Despawns an NPC
    usage: /<command> npc_id
  UnlockRecipe:
    description: Unlocks a recipe for the player character
    usage: /<command> item_id profession_id
  ShowActionbar:
    description: Shows the actionbar to the player, used for testing
    usage: /<command> offset
  SetResource:
    description: Sets the players resource
    usage: /<command> amount
  SetSpell:
    description: Sets the held items primary spell
    usage: /<command> spell_id