name: StrongholdsandEnderdragons
version: "InDev 1.0"
main: avernusvenine.sne.StrongholdsAndEnderdragons
api-version: '1.20'
commands:
  givecustomitem:
    description: Gives a custom item to the player
    usage: /<command> item_id