name: StrongholdsandEnderdragons
version: "InDev 1.1"
main: avernusvenine.sne.StrongholdsAndEnderdragons
api-version: '1.20'
commands:
  GiveCustomItem:
    description: Gives a custom item to the player
    usage: /<command> item_id
  SetRank:
    description: Sets a player to a given rank
    usage: /<command> username rank
  GetRank:
    description: Gets a players rank
    usage: /<command> username
  OpenGUI:
    description: Opens a gui to the player
    usage: /<command> gui_id